# Generated by Django 3.2.5 on 2021-07-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abridging', '0002_snippet_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='players',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
