# Generated by Django 3.2.5 on 2021-08-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abridging', '0003_videos_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnippetSound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.TextField(max_length=100)),
                ('snippet_id', models.TextField(max_length=100)),
                ('file', models.FileField(upload_to='voiceover/')),
            ],
        ),
    ]
