# Generated by Django 3.2.5 on 2021-08-03 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abridging', '0004_snippetsound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippetsound',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
