# Generated by Django 3.2.5 on 2021-08-03 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abridging', '0005_alter_snippetsound_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippetsound',
            name='file',
            field=models.FileField(max_length=500, upload_to=''),
        ),
    ]
